export type {
  AptorRole,
  Bytes32,
  ContractAddress,
  IssuerSigningKey,
  JubjubPoint,
  JubjubSchnorrSignature,
  MerkleTreeDigest,
  MerkleTreePath,
  PrivateCredentialBundleV1,
  ProofRequestV1,
  ProofReceiptV1,
  RegisteredProofRequestV1,
  SignedWorkCredentialV1,
  TransactionId,
  WorkCredentialV1,
} from "./domain.js";
